有bug未修复：发生异常: 
SystemExit
1
OSError: [Errno 98] Address already in use

During handling of the above exception, another exception occurred:

  File "/home/fonezzz/repos/ziyuan77/miaobox/download.py", line 859, in <module>
    app.run(host='0.0.0.0', port=5000, debug=True, threaded=True)  # 启动 Flask 服务 并且可以局域网访问 不要改端口！
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SystemExit: 1